### ISSUE TITLE
Roofs images do not contain capabilities

### ISSUE THREAD

**Issue by SimonDelamare** [oar-team/kameleon-bootstrap-recipes#5] opened 2016-09-02 14:42 UTC
For instance :
$ wget http://kameleon.imag.fr/rootfs/x86_64/debian8.tar.xz
$ tar -xf debian8.tar.xz ./bin/ping --selinux --acls --xattrs --xattrs-include='*'
$ getcap bin/ping
$

As a consequence, ping does not work for a normal user.

Capabilities are a "new" way to provide privileges to normal users for certain operation (before, setuid bit was used), but they are not included by tar by default (you must use  --xattrs option)

Additional information on Grid'5000 bugzilla : https://intranet.grid5000.fr/bugzilla/show_bug.cgi?id=6386

**Comment by npf** [comment] 2016-09-02 14:52
Reading the thread on g5k's bugzilla, tar should only have --selinux --xattrs --xattrs-include='*' options, no --acls. Not sure for --selinux.
However, since the tarball is extracted in the recipe which use the bootstrap, that recipe might drop the --acls and --selinux itself maybe... To test..

**Comment by npf** [comment] 2016-09-02 14:53
@mickours let me know it you do not have time to work on that issue.

**Comment by SimonDelamare** [comment] 2016-09-02 15:15
See https://github.com/grid5000/environments-recipes/pull/7 for how we can fix this for the last export as tar.gz.

**Comment by mickours** [comment] 2016-09-02 16:26
Thanks for reporting!
I just added the --selinux --xattrs --xattrs-include='*' option to the helper script. (https://github.com/oar-team/kameleon-recipes/commit/59bf157487046cccfcedab2782ead042208dbb83)

The problem is the helpers scripts are downloaded from a static tarball (which is BAD) in this bootstrap recipes but not anymore in the kameleon-recipe repo. So, I'm in a big recipe refactor and I maybe am going to merge this repository with the other to fix this issue.

**Comment by SimonDelamare** [comment] 2016-09-05 07:44
Thank you! Could you generate a new debian8.tar.xz that includes caps ?

**Comment by npf** [comment] 2016-09-22 11:25
fixed in the oar-team/kameleon-recipes repository.

**Closed as completed by npf** 2016-09-22 11:25 UTC
Labels: bug
